#!/usr/bin/python3
my_dna = "ACTGATCGATTACGTATAGTATTTGCTATCATACATATATATCGATGCGTTCAT"
length = len(my_dna)
a_count = my_dna.count('A')
t_count = my_dna.count('T')
print("length: " + str(length))
print("A count: " + str(a_count))
print("T count: " + str(t_count))
adddivide=(a_count+t_count)/length
print(adddivide)

#2
complement_dna= my_dna.replace("A","t").replace("T","a").replace("C","g").replace("G","c").upper()
print(complement_dna)
#3
cut_position=my_dna.find("GAATTC")
frag1=cut_position+1
frag2=len(my_dna)-cut_position+1
print(cut_position,frag1,frag2)
#4
mydna="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
exon1=mydna[0:63]
exon2=mydna[90:]
print("exon joined\n"+exon1+exon2)
coding_length = len(exon1 + exon2)
total_length = len(my_dna)
Codingpercentage=coding_length/total_length
print(Codingpercentage)
intron=mydna[63:90]
print(exon1+intron.lower()+exon2)

